# Application Name
spring.application.name=game

# MongoDB Connection
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/spygame_dev

# Server Port
server.port=8080
server.forward-headers-strategy=FRAMEWORK

# Gemini AI API Configuration
gemini.api.key=AIzaSyBEXr43Ra7uMttt_CTou7cAD1JJYJxraiE
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000
jwt.refresh-token.expiration=604800000

# Mail Configuration (Example using Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thuyoanh29032004@gmail.com
spring.mail.password=tyzv bgnq logv pwxu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

    
