# Application Name
spring.application.name=game

# MongoDB Connection
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/spygame_dev

# Server Port
server.port=8080
# Groq API
groq.api-key=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